/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 clown_in_car.glb -T -s -s 
Files: clown_in_car.glb [9.39MB] > clown_in_car-transformed.glb [2.14MB] (77%)
Author: KulerRuler (https://sketchfab.com/KulerRuler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/clown-in-car-94b08bdb9fb84d09908680790e9645fa
Title: clown in car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Clown(props) {
  const { nodes, materials } = useGLTF('/clown_in_car-transformed.glb')

  const ref = useRef()

  useFrame(() => {
    ref.current.rotation.z += 0.1
  })
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Ballon1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.Ballon2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Ballon3}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Hair1}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Head}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <group ref={ref} position={[0, 0.6, -0.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.material_6}
          rotation={[-Math.PI / 2, 0, 0]}
          position={[-0.03, -0.57, 0]}
        />
      </group>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.Nose}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Rope}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Znak}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.backbamper}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.backfars}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.material_12}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.bagdor}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.cabin}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.carbase}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.carfdor}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.carfront}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.chair}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.cloth1}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.cloth2}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.doors}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.farfr}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.frontbamper}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.frontbamper2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.hands1}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.hands2}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.legs}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.legs2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.legs3}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.mirrors}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.panel}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.postam}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.ruch}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.material_34}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.whell1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.whell2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.whell3}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/clown_in_car-transformed.glb')
